name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup-rdflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - uses: ./
      - run: rdflint -v

  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format-check
      - run: pnpm run type-check
      - run: pnpm run build
      - run: git diff --quiet -- dist/index.js
